# Generated by Django 2.1.2 on 2018-10-23 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('0', 'json'), ('1', 'script')], default='0', max_length=32)),
                ('name', models.CharField(max_length=256)),
                ('crisis_level', models.CharField(choices=[('0', '高危'), ('1', '危险'), ('2', '中等'), ('3', '普通')], default='0', max_length=32)),
                ('info', models.CharField(default='', max_length=256, null=True)),
                ('author', models.CharField(max_length=256)),
                ('plug_url', models.URLField()),
                ('analyzing_type', models.CharField(choices=[('0', '正则表达式'), ('1', '关键字'), ('2', 'MD5')], default='0', max_length=256)),
                ('analyzing_data', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('search_tag', models.CharField(max_length=256)),
                ('tag', models.CharField(max_length=125)),
                ('post_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlugType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='plug',
            name='plug_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plug.PlugType'),
        ),
    ]
