# Generated by Django 2.1.2 on 2018-10-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plug',
            name='script_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
