# Generated by Django 2.1.2 on 2018-10-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plug', '0002_plug_script_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonPlug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('crisis_level', models.CharField(choices=[('0', '高危'), ('1', '危险'), ('2', '中等'), ('3', '普通')], default='0', max_length=32)),
                ('info', models.CharField(default='', max_length=256, null=True)),
                ('author', models.CharField(max_length=256)),
                ('plug_url', models.URLField()),
                ('analyzing_type', models.CharField(choices=[('0', '正则表达式'), ('1', '关键字'), ('2', 'MD5')], default='0', max_length=256)),
                ('analyzing_data', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('search_tag', models.CharField(max_length=256)),
                ('tag', models.CharField(max_length=125)),
                ('post_data', models.TextField()),
                ('script_file', models.FileField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ScriptPlug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('script_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='plug',
            name='plug_type',
        ),
    ]
