# Generated by Django 2.1.2 on 2018-10-25 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plug', '0003_auto_20181025_0556'),
        ('task', '0003_auto_20181025_0556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plug',
        ),
        migrations.AddField(
            model_name='scriptplug',
            name='plug_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plug.PlugType'),
        ),
        migrations.AddField(
            model_name='jsonplug',
            name='plug_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plug.PlugType'),
        ),
    ]
