# Generated by Django 2.1.2 on 2018-11-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plug', '0004_auto_20181025_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plugtype',
            old_name='type',
            new_name='p_type',
        ),
    ]
