# Generated by Django 2.1.2 on 2018-11-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plug', '0005_auto_20181101_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonplug',
            name='script_file',
        ),
        migrations.AlterField(
            model_name='jsonplug',
            name='post_data',
            field=models.TextField(default=''),
        ),
    ]
