# Generated by Django 2.1.2 on 2018-11-01 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plug', '0007_plugtype_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugtype',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jsonplug',
            name='plug_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='json_plug', to='plug.PlugType'),
        ),
        migrations.AlterField(
            model_name='scriptplug',
            name='plug_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='script_plug', to='plug.PlugType'),
        ),
    ]
