# Generated by Django 2.1.2 on 2018-11-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plug', '0008_auto_20181101_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugtype',
            name='content',
            field=models.CharField(default='', max_length=256),
        ),
    ]
