# Generated by Django 2.1.2 on 2018-11-07 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plug', '0010_plugtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonplug',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
