# Generated by Django 2.0.3 on 2018-11-28 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plug', '0011_jsonplug_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptplug',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scriptplug',
            name='script_file',
            field=models.FileField(upload_to='plug/'),
        ),
    ]
