# Generated by Django 2.0.3 on 2018-11-28 06:33

from django.db import migrations, models
import plug.models


class Migration(migrations.Migration):

    dependencies = [
        ('plug', '0012_auto_20181128_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptplug',
            name='taken',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scriptplug',
            name='script_file',
            field=models.FileField(upload_to=plug.models.get_file_path),
        ),
    ]
