# Generated by Django 2.1.2 on 2018-10-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plug', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('run_times', models.CharField(choices=[('0', '每天'), ('1', '每周一次'), ('2', '每月一次')], default='0', max_length=32)),
                ('is_auto_flush', models.BooleanField(default=False)),
                ('task_type', models.CharField(max_length=256)),
                ('crisis_level', models.CharField(choices=[('0', '高危'), ('1', '危险'), ('2', '中等'), ('3', '普通')], default='0', max_length=32)),
                ('target', models.CharField(max_length=256)),
                ('plugs', models.ManyToManyField(to='plug.Plug')),
            ],
        ),
    ]
