# Generated by Django 2.1.2 on 2018-10-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='port',
            field=models.IntegerField(default=80),
        ),
    ]
