# Generated by Django 2.0.3 on 2018-11-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20181025_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='json_plugs',
            field=models.ManyToManyField(blank=True, default=None, to='plug.JsonPlug'),
        ),
        migrations.AlterField(
            model_name='task',
            name='script_plugs',
            field=models.ManyToManyField(blank=True, default=None, to='plug.ScriptPlug'),
        ),
    ]
