# Generated by Django 2.0.3 on 2018-11-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20181101_1110'),
        ('task', '0004_auto_20181101_1938'),
    ]

    operations = [
    ]
